# ----------------
# Stage 1: Build
# ----------------
FROM node:18.20-alpine AS build

# Создадим рабочую директорию
WORKDIR /app

# Скопируем package*.json для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальной код (контекст сборки – корень проекта)
COPY . .

# Собираем production-версию
RUN npm run build:classic

# ----------------
# Stage 2: Production
# ----------------
FROM nginx:alpine as production

# Копируем статические файлы из Stage 1 в стандартную директорию Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Копируем конфигурационный файл nginx, который лежит в папке infra
COPY infra/nginx.classic.conf /etc/nginx/conf.d/default.conf

# Открываем порт 443 (HTTPS)
EXPOSE 80

# Запуск Nginx в переднем режиме
CMD ["nginx", "-g", "daemon off;"]
