version: "3.7"

services:
  pwa:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: pwa
    ports:
      - "443:443"
    networks:
      - monitoring-net

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/infra/:/var/lib/infra:ro
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring-net

  browser:
    image: jlesage/firefox
    container_name: browser
    restart: unless-stopped
    ports:
      - "5800:5800"   # noVNC доступ для визуального управления браузером
    environment:
      - TZ=Europe/Moscow  # настройка часового пояса (при необходимости)
    networks:
      - monitoring-net

  e2e:
    image: cypress/included:12.3.0
    container_name: e2e
    depends_on:
      - pwa
    environment:
      - CYPRESS_BASE_URL=https://pwa:443
    working_dir: /e2e
    volumes:
      - ../:/e2e
    command: ["cypress", "run", "--browser", "chrome"]# команда запуска тестов
    networks:
      - monitoring-net

networks:
  monitoring-net: