{
 "title": "cAdvisor",
 "description": "Все метрики из cAdvisors",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Network (общий)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[1m]) + rate(container_network_transmit_bytes_total[1m])) by (container) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (Исходящий трафик)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[1m])) by (container) /(1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (Входящий трафик)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[1m])) by (container) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Core",
   "type": "timeseries",
   "description": "Использование CPU по ядрам",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (container, cpu) (rate(container_cpu_usage_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Использование мощности процессора (в процентах)",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[1m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "description": "Использование оперативной памяти (в мегабайтах)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes) by (container) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}