{
 "title": "cAdvisor by container",
 "description": "Все метрики из cAdvisors",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container Id",
    "query": "/docker/bcc83005087f8482a331f6597e6aebb2c3d237f7243f51a75217cef1bc8050eb"
   }
  ]
 },
 "panels": [
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum(\r\n    rate(container_network_receive_bytes_total{id=~\"$container\"}[1m])\r\n    +\r\n    rate(container_network_transmit_bytes_total{id=~\"$container\"}[1m])\r\n  ),\r\n  \"legend\", \"Network Total\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(rate(container_network_receive_bytes_total{id=~\"$container\"}[1m])), \"legend\", \"Network Receive\", \"\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(rate(container_network_transmit_bytes_total{id=~\"$container\"}[1m])), \"legend\", \"Network Transmit\", \"\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Core",
   "type": "timeseries",
   "description": "Использование CPU по ядрам",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (cpu) (rate(container_cpu_usage_seconds_total{id=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU total usage",
   "type": "timeseries",
   "description": "Использование мощности процессора (в процентах)",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "description": "Использование оперативной памяти (в мегабайтах)",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id=~\"$container\"}) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}