{
 "title": "Two containers comparison",
 "description": "Все метрики из cAdvisors",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "container_1", "label": "Контейнер 1", "query": { "query": "label_values(name)" } },
   { "name": "container_2", "label": "Контейнер 2", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum(\r\n    rate(container_network_receive_bytes_total{name=\"$container_1\", interface=~\"eth0|eth2\"}[30s])\r\n    +\r\n    rate(container_network_transmit_bytes_total{name=~\"$container_1\", interface=~\"eth0|eth2\"}[30s])\r\n  ) / 1024,\r\n  \"legend\", \"Сетевой трафик ($container_1)\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(rate(container_network_receive_bytes_total{name=\"$container_1\", interface=~\"eth0|eth2\"}[30s])) / 1024, \"legend\", \"Прием ($container_1)\", \"\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(rate(container_network_transmit_bytes_total{name=~\"$container_1\", interface=~\"eth0|eth2\"}[30s])) / 1024, \"legend\", \"Передача ($container_1)\", \"\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(\r\n    rate(container_network_receive_bytes_total{name=\"$container_2\", interface=~\"eth0|eth2\"}[30s])\r\n    +\r\n    rate(container_network_transmit_bytes_total{name=~\"$container_2\", interface=~\"eth0|eth2\"}[30s])\r\n  ) / 1024,\r\n  \"legend\", \"Сетевой траффик ($container_2)\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(rate(container_network_receive_bytes_total{name=\"$container_2\", interface=~\"eth0|eth2\"}[30s])) /1024, \"legend\", \"Прием ($container_2)\", \"\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(rate(container_network_transmit_bytes_total{name=~\"$container_2\", interface=~\"eth0|eth2\"}[30s])) /1024, \"legend\", \"Передача ($container_2)\", \"\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU total usage",
   "type": "timeseries",
   "description": "Использование мощности процессора (в процентах)",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{name=~\"$container_1\"}[30s])), \"legend\", \"CPU ($container_1)\", \"\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{name=~\"$container_2\"}[30s])), \"legend\", \"CPU ($container_2)\", \"\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "description": "Использование оперативной памяти (в мегабайтах)",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_usage_bytes{name=~\"$container_1\"}) / (1024 * 1024), \"legend\", \"RAM ($container_1)\", \"\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(container_memory_usage_bytes{name=~\"$container_2\"}) / (1024 * 1024), \"legend\", \"RAM ($container_2)\", \"\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}